In [58]:
def hap(g,t,n):
    google=pd.read_csv(g)
    google=google[['STAR','CONTENT']]
    trip=pd.read_csv(t,encoding='cp949')
    trip=trip[['별점','리뷰']]
    trip.columns=['STAR','CONTENT']
    hap=google.append(trip).reset_index(drop=True)
    print(hap)
    hap.to_csv(n+'.csv')

In [59]:
hap("C:/Users/wndgm/Documents/GitHub/2022_DATA_TEAM5/HS/크롤링/final Namdaemun Market review.csv",
    "C:/Users/wndgm/Documents/GitHub/2022_DATA_TEAM5/HS/크롤링/Namdaemun Market_tripadvisor.csv",
    'Namdaemun Market')

     STAR                                            CONTENT
0       4  Shopping heaven but not many signboard for dir...
1       5   Namdaemun is often used because of its variet...
2       4   There are many things to see and it is good C...
3       3   It is a traditional market for a long time an...
4       5   Its always good to walk It has a wide variety...
..    ...                                                ...
618     5  When you love bargain items, this is a must vi...
619     5  Namdaemun is one of the best markets to visit ...
620     1  This market is full of counterfeited goods and...
621     5  I am so amazed in this very clean market. I en...
622     5  This market seems to be a lower market compare...

[623 rows x 2 columns]

In [55]:
import pandas as pd
#a=pd.read_csv("C:/Users/wndgm/Documents/GitHub/2022_DATA_TEAM5/HS/크롤링/final Namdaemun Market review.csv")
b=pd.read_csv("C:/Users/wndgm/Documents/GitHub/2022_DATA_TEAM5/HS/크롤링/Namdaemun Market_tripadvisor.csv",encoding='cp949')
#a
b

,Unnamed: 0,이름,별점,리뷰,날짜
0,0,Brian J,5,If you want to experience shopping at a tradit...,"Written July 7, 2022"
1,1,Traveller of the world,3,I am not one for markets. I came as it is appa...,"Written May 30, 2022"
2,2,Gigi C,4,Fun place to walk around and shop. Dedicated s...,"Written May 14, 2022"
3,3,AuthurTommy,3,It's not so easy to track if it's first time. ...,"Written August 31, 2020"
4,4,rememr,3,Went here mainly to buy dried food such as the...,"Written August 10, 2020"
...,...,...,...,...,...
345,345,aldasafira,5,"When you love bargain items, this is a must vi...","Written May 14, 2018"
346,346,Seoulinspired,5,Namdaemun is one of the best markets to visit ...,"Written May 14, 2018"
347,347,Garfieldluvr,1,This market is full of counterfeited goods and...,"Written May 13, 2018"
348,348,RoniRomero,5,I am so amazed in this very clean market. I en...,"Written May 12, 2018"
349,349,Acineto,5,This market seems to be a lower market compare...,"Written May 11, 2018"

In [12]:
a=a[['STAR','CONTENT']]
b=b[['별점','리뷰']]
b.columns=['STAR','CONTENT']

In [13]:
c=a.append(b)
c

      STAR                                            CONTENT
0      5.0  Seoul tower is very peacfull and one of clean ...
1      4.0   We have walked up and down It is a good walk ...
2      4.0   It was a bit late to open and it was raining ...
3      5.0   It was nice to be able to see the beautiful n...
4      5.0  Got there at dusk By the time we got into the ...
...    ...                                                ...
5205   3.0  when I visit here there is no cherry blossoms ...
5206   4.0  It gives a beautiful view of the city. It is b...
5207   4.0  great view from the observatory, yet Tokyo tow...
5208   5.0  There are good trails around here and amazing ...
5209   3.0  The view was OK...it was very very crowded up ...

[5508 rows x 2 columns]

In [54]:
open("C:/Users/wndgm/Documents/GitHub/2022_DATA_TEAM5/HS/크롤링/Namdaemun Market_tripadvisor.csv", 'rt', encoding='UTF8')