In [73]:
import pandas as pd

In [74]:
df=pd.read_csv('C:/Users/gkxmr/topic4_쇼핑/토픽4감성분석.csv')

In [75]:
df

    Unnamed: 0               긍정  리뷰 수                 부정  리뷰 수.1
0            0         night/NN  1024          boring/NN      21
1            1       things/NNS   163          fewer/JJR       9
2            2          walk/NN  1379       admission/NN      39
3            3         quiet/JJ    81          almost/RB      68
4            4       amazing/JJ   290           need/VBP     243
5            5          trip/NN   271         weekend/NN     169
6            6  restaurants/NNS   404          normal/JJ      15
7            7       library/NN    26            trap/NN      37
8            8     sometimes/RB    20             ive/JJ     783
9            9   comfortable/JJ    46           ride/VBP     487
10          10           day/NN   944  dissepoinding/VBG       1
11          11        corona/NN    54            dust/NN      11
12          12         dont/VBP   270           every/DT     311
13          13        spring/NN    84           sadly/RB       2
14          14    strolling/VBG    23            cool/NN     195
15          15     recommend/VB   398       namsangol/NN       1
16          16     different/JJ   154           emptu/NN       1
17          17       leisure/NN    25             dep/NN      62
18          18      enjoyed/VBD   197    surrounding/VBG      81
19          19          easy/JJ   154            long/RB     603
20          20         along/IN   163             bus/JJ     789
21          21         used/VBD    71        waiting/VBG     117
22          22    souvenirs/NNS   119            long/JJ     603
23          23       opening/NN    12             top/JJ    1105
24          24       morning/NN   114         nothing/NN      91
25          25          full/JJ   187        crowded/VBN     365
26          26         came/VBD   144        visited/VBN     226
27          27           eat/VB  1344          rides/NNS      89
28          28        around/RB   655   expectations/NNS       8
29          29        namsan/RB    47         seemed/VBD      26
30          30        family/NN   139            ride/NN     487
31          31          walk/VB  1379     observatory/NN     156
32          32    incredible/JJ    30            base/NN     218
33          33       weather/NN   209           took/VBD     396
34          34         photo/NN   298        probably/RB      52
35          35           may/MD   132            rest/VB     881
36          36   opportunity/NN    49            soso/JJ       8
37          37       adults/NNS    25            much/JJ     344
38          38          rare/JJ     5             due/JJ     103
39          39         board/NN    37           money/NN      85
40          40            pm/NN   159        minutes/NNS     183
41          41    accessible/JJ    59          seems/VBZ      54
42          42       explore/VB    55               n/JJ    4971
43          43        nature/NN    63       tourists/NNS     143
44          44        highly/RB    60            okay/NN      22
45          45         walk/VBP  1379           could/MD     235
46          46       stores/NNS    61            hill/NN     480
47          47         lost/VBN    40           kids/NNS     117
48          48         felt/VBD    65           queue/NN     237
49          49    mountains/NNS    38             bus/NN     789

In [115]:
df2=pd.read_csv('C:/Users/gkxmr/topic4_쇼핑/Times Square Mall words.csv')

In [116]:
df2

    Unnamed: 0                긍정  리뷰 수              부정  리뷰 수.1
0            0            one/CD  18.0         high/JJ      13
1            1       options/NNS   6.0      western/JJ       2
2            2        square/VBP   4.0       indoor/NN       2
3            3        brands/NNS  12.0        first/JJ       5
4            4         really/RB   5.0         even/RB      11
5            5           huge/JJ  14.0         dont/NN       4
6            6            big/JJ  16.0          go/VBP      32
7            7          movie/NN   8.0        check/VB       2
8            8           food/NN  21.0            3/CD       6
9            9           line/NN   7.0        stick/JJ       1
10          10        parking/NN   4.0      special/JJ       4
11          11  entertainment/NN   7.0    otherwise/RB       2
12          12         hours/NNS   6.0         mega/JJ       1
13          13      excellent/JJ   1.0        close/NN       9
14          14     affordable/JJ   5.0      central/JJ       1
15          15          court/NN  11.0         year/NN       3
16          16         choose/VB   4.0    otherwise/IN       2
17          17         times/NNS   7.0          one/NN      18
18          18          best/JJS   4.0     koreans/NNS       0
19          19           seul/NN   0.0     horrible/JJ       1
20          20       parking/VBG   4.0   countdown/VBP       1
21          21          range/NN   5.0         area/NN       6
22          22         subway/NN   9.0    afternoon/NN       2
23          23    interesting/JJ   3.0        local/JJ       4
24          24          hotel/NN   5.0     minutes/NNS       2
25          25          enjoy/VB  10.0        large/JJ      10
26          26      hundreds/NNS   2.0       border/NN       1
27          27         number/NN   3.0     basement/NN       7
28          28          want/VBP   5.0      weather/NN       3
29          29      courtyard/NN   0.0         sale/NN       4
30          30        another/DT   3.0      things/NNS       4
31          31           got/VBD   3.0         home/NN       2
32          32           alot/NN   1.0      outside/IN       5
33          33        theatre/NN   3.0        youre/NN       4
34          34          price/NN   9.0    wednesday/JJ       0
35          35        theres/VBZ   0.0         slot/NN       1
36          36           cgv/NNS   0.0    practical/JJ       1
37          37           shop/VB  48.0  convenience/NN       1
38          38             go/VB  32.0          new/JJ       2
39          39               NaN   NaN        took/VBD       2
40          40               NaN   NaN     familiar/JJ       1
41          41               NaN   NaN        worth/IN       4
42          42               NaN   NaN          get/VB      12
43          43               NaN   NaN      stores/NNS      16
44          44               NaN   NaN           pm/NN       1

In [117]:
'''k=0
po=[]
ne=[]
num_p=[]
num_n=[]
a=0
for i in df.index:
    for j in df2.index:
        if df['긍정'][i]==df2['긍정'][j]:
            po.append(df['긍정'][i])
            num_p.append(df['리뷰 수'][i])
            print('기준 긍정토픽은', df['긍정'][i], '기준인덱스는', i, '리뷰수는', df['리뷰 수'][i],'비교인덱스는',j,'비교리뷰수',
                 df2['리뷰 수.1'][j])
            #print('기준 긍정토픽은', po[a], '기준인덱스는', i, '리뷰수는', num_p[a],'비교인덱스는',j)
            a=a+1
        if df['부정'][i]==df2['부정'][j]:
            ne.append(df['부정'][i])
            num_n.append(df['리뷰 수.1'][i])
            print('기준 부정토픽은',df['부정'][i],'기준인덱스는',i,'리뷰수는',df['리뷰 수.1'][i],'비교인덱스는',j)'''

"k=0\npo=[]\nne=[]\nnum_p=[]\nnum_n=[]\na=0\nfor i in df.index:\n    for j in df2.index:\n        if df['긍정'][i]==df2['긍정'][j]:\n            po.append(df['긍정'][i])\n            num_p.append(df['리뷰 수'][i])\n            print('기준 긍정토픽은', df['긍정'][i], '기준인덱스는', i, '리뷰수는', df['리뷰 수'][i],'비교인덱스는',j,'비교리뷰수',\n                 df2['리뷰 수.1'][j])\n            #print('기준 긍정토픽은', po[a], '기준인덱스는', i, '리뷰수는', num_p[a],'비교인덱스는',j)\n            a=a+1\n        if df['부정'][i]==df2['부정'][j]:\n            ne.append(df['부정'][i])\n            num_n.append(df['리뷰 수.1'][i])\n            print('기준 부정토픽은',df['부정'][i],'기준인덱스는',i,'리뷰수는',df['리뷰 수.1'][i],'비교인덱스는',j)"

In [118]:
k1=0
po1=[]
ne1=[]
num_p1=[]
num_n1=[]
a=0
for i in df.index:
    for j in df2.index:
        if df['긍정'][i]==df2['부정'][j]:
            po1.append(df['긍정'][i])
            num_p1.append(df['리뷰 수'][i])
            print('기준 긍정토픽은', df['긍정'][i], '기준인덱스는', i, '리뷰수는', df['리뷰 수'][i],'비교인덱스는',j,'비교리뷰수',
                 df2['리뷰 수.1'][j])
            #print('기준 긍정토픽은', po[a], '기준인덱스는', i, '리뷰수는', num_p[a],'비교인덱스는',j)
        if df['부정'][i]==df['긍정'][j]:
            ne1.append(df['부정'][i])

기준 긍정토픽은 things/NNS 기준인덱스는 1 리뷰수는 163 비교인덱스는 30 비교리뷰수 4
기준 긍정토픽은 weather/NN 기준인덱스는 33 리뷰수는 209 비교인덱스는 28 비교리뷰수 3
기준 긍정토픽은 pm/NN 기준인덱스는 40 리뷰수는 159 비교인덱스는 44 비교리뷰수 1
기준 긍정토픽은 stores/NNS 기준인덱스는 46 리뷰수는 61 비교인덱스는 43 비교리뷰수 16

In [119]:

print('혜정긍정 준혁부정',po1)
print('혜정부정 준혁긍정',ne1)

혜정긍정 준혁부정 ['things/NNS', 'weather/NN', 'pm/NN', 'stores/NNS']
혜정부정 준혁긍정 []

In [361]:
save1=pd.DataFrame({'긍정':po,
                    '리뷰수':num_p,})
save2=pd.DataFrame({'부정':ne,
                      '리뷰수':num_n})

In [362]:
save=pd.concat([save1,save2])

In [363]:
save

            긍정  리뷰수               부정
0  enjoyed/VBN  145              NaN
1     spend/VB   99              NaN
2      take/VB  253              NaN
3    loved/VBD   55              NaN
4      full/JJ  102              NaN
5   walking/NN  144              NaN
0          NaN   19         empty/JJ
1          NaN   44  disappointed/JJ
2          NaN  276          much/JJ
3          NaN   40       nothing/NN
4          NaN   31  disappointed/JJ
5          NaN   32       however/RB
6          NaN   89       nothing/NN

In [347]:
save.to_csv("토픽2_전쟁기념관.csv")